imports:
    - { resource: parameters.yml }

services:
    andreask.secretx.controller.main:
        class: andreask\secretx\controller\main_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '@request'
            - '@controller.helper'
            - '@template'
            - '@language'
            - '@notification_manager'

    andreask.secretx.controller.acp:
        class: andreask\secretx\controller\acp_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    andreask.secretx.service:
        class: andreask\secretx\service
        arguments:
            - '@user'

    andreask.secretx.listener:
        class: andreask\secretx\event\main_listener
        arguments:
            - '@language'
            - '@config'
            - '@controller.helper'
            - '@template'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    andreask.secretx.notification.type.inform_organizer:
        class: andreask\secretx\notification\type\inform_organizer
        shared: false # service MUST not be shared for this to work!
        parent: notification.type.base
        calls:
            - [set_controller_helper, ['@controller.helper']]
        tags:
            - { name: notification.type }
